version: "3"
services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - PGUSER=zakgogi
      - PGHOST=db
      - PGPASSWORD=scorepass97
      - PGDATABASE=scores
      - DATABASE_URL=postgres://zakgogi:scorepass97@db:5432/scores
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"

  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=scores
      - POSTGRES_USER=zakgogi
      - POSTGRES_PASSWORD=scorepass97
volumes:
  dbdata:
